from common import common
from db.database import singleton_Results_DB


def __createTable():
    sql = '''create table if not exists {}(
    id INT PRIMARY KEY AUTO_INCREMENT,
    race_id INT DEFAULT 0,
    horse_no INT DEFAULT 0,
    pla_odds FLOAT DEFAULT 0,
    win_odds FLOAT DEFAULT 0,
    plc INT DEFAULT 0,
    current_rating INT DEFAULT 0,
    odd_old FLOAT DEFAULT 0,
    odd_wave FLOAT DEFAULT 0,
    dct_trend INT DEFAULT 0,
    rating_trend INT DEFAULT 0,
    declar_horse_wt INT DEFAULT 0,
    actual_wt INT DEFAULT 0,
    rest INT DEFAULT 0,
    horse_record_total INT DEFAULT 0,
    horse_dst_record_total INT DEFAULT 0,
    horse_cls_record_total INT DEFAULT 0,
    trainer_record_total INT DEFAULT 0,
    jockey_record_total INT DEFAULT 0,
    jockey_recent_total INT DEFAULT 0,
    draw_record_total INT DEFAULT 0,
    horse_best_speed FLOAT DEFAULT 0,
    same_trainer_count INT DEFAULT 0,
    horse_recent_total INT DEFAULT 0,
    horse_going_record_total INT DEFAULT 0,
    jockey_fav_record_total INT DEFAULT 0,
    horse_gear_record_total INT DEFAULT 0,
    horse_track_record_total INT DEFAULT 0,
    trainer_recent_total INT DEFAULT 0,
    horse_fav_record_total INT DEFAULT 0,
    horse_track_fav_record_total INT DEFAULT 0,
    trainer_fav_record_total INT DEFAULT 0,
    track_record_total INT DEFAULT 0,
    horse_dst_record_before4 INT DEFAULT 0,
    horse_cls_record_before4 INT DEFAULT 0,
    trainer_record_before4 INT DEFAULT 0,
    jockey_record_before4 INT DEFAULT 0,
    jockey_recent_before4 INT DEFAULT 0,
    draw_record_before4 INT DEFAULT 0,
    horse_recent_before4 INT DEFAULT 0,
    horse_going_record_before4 INT DEFAULT 0,
    jockey_fav_record_before3 INT DEFAULT 0,
    horse_gear_record_before4 INT DEFAULT 0,
    horse_track_record_before4 INT DEFAULT 0,
    trainer_recent_before4 INT DEFAULT 0,
    horse_fav_record_before3 INT DEFAULT 0,
    horse_track_fav_record_before3 INT DEFAULT 0,
    trainer_fav_record_before3 INT DEFAULT 0,
    track_fav_record_before3 INT DEFAULT 0,
    horse_best_recent_speed FLOAT DEFAULT 0,
    race_date INT DEFAULT 0,
    race_no INT DEFAULT 0,
    horse_code VARCHAR(45) DEFAULT '',
    trainer VARCHAR(45) DEFAULT '',
    jockey VARCHAR(45) DEFAULT '',
    site VARCHAR(45) DEFAULT '',
    going VARCHAR(45) DEFAULT '',
    course VARCHAR(45) DEFAULT '',
    dst int DEFAULT 0,
    cls VARCHAR(45) DEFAULT '',
    draw INT DEFAULT 0,
    gear VARCHAR(45) DEFAULT '',
    lbw VARCHAR(45) DEFAULT '',
    finish_time INT DEFAULT 0,
    over_wt VARCHAR(45) DEFAULT '',
    cls_standard_speed FLOAT DEFAULT 0,
    pedigree_dst INT DEFAULT 0,
    pedigree_track INT DEFAULT 0,
    fav_match INT DEFAULT 0,
    odd_diff FLOAT DEFAULT 0,
    jockey_trainer_record_total INT DEFAULT 0,
    horse_recent_record_total INT DEFAULT 0,
    horse_go_record_total INT DEFAULT 0,
    jockey_hot INT DEFAULT 0,
    horse_site_record_total INT DEFAULT 0,
    horse_course_record_total INT DEFAULT 0,
    horse_draw_record_total INT DEFAULT 0,
    horse_jockey_record_total INT DEFAULT 0,
    jockey_trainer_record_before4 INT DEFAULT 0,
    horse_recent_record_before4 INT DEFAULT 0,
    horse_go_record_before4 INT DEFAULT 0,
    horse_site_record_before4 INT DEFAULT 0,
    horse_course_record_before4 INT DEFAULT 0,
    horse_draw_record_before4 INT DEFAULT 0,
    horse_jockey_record_before4 INT DEFAULT 0,
    horse_lowest_speed FLOAT DEFAULT 0,
    horse_avr_speed FLOAT DEFAULT 0,
    horse_recent_best_speed FLOAT DEFAULT 0,
    horse_recent_lowest_speed FLOAT DEFAULT 0,
    horse_recent_avr_speed FLOAT DEFAULT 0,
    horse_site_best_speed FLOAT DEFAULT 0,
    horse_site_lowest_speed FLOAT DEFAULT 0,
    horse_site_avr_speed FLOAT DEFAULT 0,
    horse_go_best_speed FLOAT DEFAULT 0,
    horse_go_lowest_speed FLOAT DEFAULT 0,
    horse_go_avr_speed FLOAT DEFAULT 0,
    horse_course_best_speed FLOAT DEFAULT 0,
    horse_course_lowest_speed FLOAT DEFAULT 0,
    horse_course_avr_speed FLOAT DEFAULT 0,
    horse_dst_best_speed FLOAT DEFAULT 0,
    horse_dst_lowest_speed FLOAT DEFAULT 0,
    horse_dst_avr_speed FLOAT DEFAULT 0,
    horse_cls_best_speed FLOAT DEFAULT 0,
    horse_cls_lowest_speed FLOAT DEFAULT 0,
    horse_cls_avr_speed FLOAT DEFAULT 0,
    horse_draw_best_speed FLOAT DEFAULT 0,
    horse_draw_lowest_speed FLOAT DEFAULT 0,
    horse_draw_avr_speed FLOAT DEFAULT 0,
    horse_gear_best_speed FLOAT DEFAULT 0,
    horse_gear_lowest_speed FLOAT DEFAULT 0,
    horse_gear_avr_speed FLOAT DEFAULT 0,
    horse_jockey_best_speed FLOAT DEFAULT 0,
    horse_jockey_lowest_speed FLOAT DEFAULT 0,
    horse_jockey_avr_speed FLOAT DEFAULT 0,
    horse_last_dst_time_prev FLOAT DEFAULT 0,
    horse_last_dst_time_min FLOAT DEFAULT 0,
    horse_last_dst_time_ave FLOAT DEFAULT 0)'''.format(common.ODDS_MODEL45_TABLE)
    singleton_Results_DB.cursor.execute(sql)


def exportToModel45Table(all_list):
    if singleton_Results_DB.table_exists(common.ODDS_MODEL45_TABLE):
        singleton_Results_DB.cursor.execute('drop table {}'.format(common.ODDS_MODEL45_TABLE))
        singleton_Results_DB.connect.commit()
    __createTable()
    inster_sql = '''insert into {}(race_id, horse_no, pla_odds, win_odds, plc, current_rating, odd_old, 
    odd_wave, dct_trend, rating_trend, declar_horse_wt, actual_wt, rest, horse_record_total, 
    horse_dst_record_total, horse_cls_record_total, trainer_record_total, jockey_record_total, 
    jockey_recent_total, draw_record_total,
    horse_best_speed, same_trainer_count, horse_recent_total, horse_going_record_total,
    jockey_fav_record_total, horse_gear_record_total, horse_track_record_total, trainer_recent_total,
    horse_fav_record_total, horse_track_fav_record_total, trainer_fav_record_total, track_record_total,
    horse_dst_record_before4, horse_cls_record_before4, trainer_record_before4, jockey_record_before4,
    jockey_recent_before4, draw_record_before4, horse_recent_before4, horse_going_record_before4,
    jockey_fav_record_before3, horse_gear_record_before4, horse_track_record_before4, 
    trainer_recent_before4, horse_fav_record_before3, horse_track_fav_record_before3,
    trainer_fav_record_before3, track_fav_record_before3, horse_best_recent_speed, race_date, race_no,
    horse_code, trainer, jockey, site, going, course, dst, cls, draw, gear, lbw, finish_time, over_wt, 
    cls_standard_speed, pedigree_dst, pedigree_track, fav_match, odd_diff, jockey_trainer_record_total, 
    horse_recent_record_total, horse_go_record_total, jockey_hot, horse_site_record_total, 
    horse_course_record_total, horse_draw_record_total, horse_jockey_record_total, 
    jockey_trainer_record_before4, horse_recent_record_before4, horse_go_record_before4, 
    horse_site_record_before4, horse_course_record_before4, horse_draw_record_before4,
    horse_jockey_record_before4, horse_lowest_speed, horse_avr_speed, horse_recent_best_speed, 
    horse_recent_lowest_speed, horse_recent_avr_speed, horse_site_best_speed, horse_site_lowest_speed, 
    horse_site_avr_speed, horse_go_best_speed, horse_go_lowest_speed, horse_go_avr_speed, 
    horse_course_best_speed, horse_course_lowest_speed, horse_course_avr_speed, horse_dst_best_speed, 
    horse_dst_lowest_speed, horse_dst_avr_speed, horse_cls_best_speed, horse_cls_lowest_speed, 
    horse_cls_avr_speed, horse_draw_best_speed, horse_draw_lowest_speed, horse_draw_avr_speed, 
    horse_gear_best_speed, horse_gear_lowest_speed, horse_gear_avr_speed, horse_jockey_best_speed, 
    horse_jockey_lowest_speed, horse_jockey_avr_speed, horse_last_dst_time_prev, 
    horse_last_dst_time_min, horse_last_dst_time_ave)
    values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'''.format(common.ODDS_MODEL45_TABLE)   #116个
    singleton_Results_DB.cursor.executemany(inster_sql, all_list)
    singleton_Results_DB.connect.commit()

